name: Mushroom Claimer Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Playwright browsers + dependencies
          python -m playwright install --with-deps

      - name: Run mushroom bot
        env:
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          CLAIM_URL: ${{ secrets.CLAIM_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          USERNAME_1: ${{ secrets.USERNAME_1 }}
          PASSWORD_1: ${{ secrets.PASSWORD_1 }}
          USERNAME_2: ${{ secrets.USERNAME_2 }}
          PASSWORD_2: ${{ secrets.PASSWORD_2 }}
        run: python bot.py
